# Use the builder image as a data source
# Note: osrm-data-builder must be available in the local registry
ARG BUILDPLATFORM
FROM --platform=$BUILDPLATFORM osrm-data-builder AS data

FROM --platform=linux/amd64 ghcr.io/project-osrm/osrm-backend:latest

ARG PROFILE=car
ENV PROFILE=${PROFILE}
ARG OSM_FILE=costa-rica-latest.osm.pbf
ENV OSM_BASE=${OSM_FILE%.osm.pbf}

COPY --from=data /data /data

WORKDIR /data/${PROFILE}
