"""Reading the real-world catalogue as data — `CAT-VRP-003` §0, §13.6.

The catalogue's §1 says its entries "do double duty: they justify requirements
in the design document, and they specify fixtures for the test corpus." Until
this module existed only the first half happened: 741 VRP tests and not one of
them knew a `UC-nnn` existed, so nothing could report a requirement landing with
no operation behind it.

`scenarios.jsonl` is the surface, not the prose. §0.2 calls it "the retrieval
and filtering surface" and §0.5 lists the questions it is meant to answer, so
the query helpers below are that table rather than an invention: tier, variant,
citing requirement, and status.

**The extract is read, never re-derived.** It is generated by
`docs/TDD/build_catalogue.py` from the authored source and validated on build,
so parsing the markdown again here would be a second implementation of a parser
that already fails the build on drift. `make catalogue` is the only writer.

**Pathological entries are not operational scenarios.** §11's fifteen adversarial
instances carry the `PATHOLOGICAL` variant so they can be selected as a set and
excluded from the variant audit; `operational` and `pathological` are the two
halves and every count here says which it means.

Placement: **Python**, per criterion 2. This reads a documentation artefact and
feeds the test corpus; it is nowhere near a request path, and it changes when
the catalogue's schema does.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SCENARIOS = REPO / "docs" / "TDD" / "scenarios.jsonl"
SPEC = REPO / "docs" / "vrp-spec-driven-development.md"

PATHOLOGICAL = "PATHOLOGICAL"

# §3 of the design document, one requirement per table row. Anchored on the row
# start so a mention in prose is not mistaken for a definition -- and with a
# lookbehind, because `NFR-04` contains `FR-04` and the catalogue's own builder
# was extracting the one from the other until `UC-072` cited a real NFR.
SPEC_REQUIREMENT = re.compile(r'^\| `(FR-\d+)` \|', re.MULTILINE)


@dataclass(frozen=True)
class Scenario:
    """One catalogue entry. Fields mirror §0.3's schema exactly."""

    id: str
    name: str
    tier: str
    variant: str
    tags: tuple[str, ...]
    section: str
    description: str
    binds: str
    exercises_raw: str
    requirements: tuple[str, ...]
    breaks: str
    status: str
    status_note: str

    @property
    def is_pathological(self) -> bool:
        return self.variant == PATHOLOGICAL


def load(path: Path | None = None) -> tuple[Scenario, ...]:
    """Read the extract in document order.

    Args:
        path: override for the extract. Defaults to the committed one.

    Returns:
        Every entry, including the adversarial instances of §11.

    Raises:
        FileNotFoundError: if the extract is missing. It is generated by
            `make catalogue` and committed, so its absence is a broken
            checkout rather than a state to degrade through.
    """
    source = path or SCENARIOS
    rows = [json.loads(line) for line in source.read_text().splitlines() if line]
    return tuple(Scenario(id=row["id"], name=row["name"], tier=row["tier"],
                          variant=row["variant"], tags=tuple(row["tags"]),
                          section=row["section"], description=row["description"],
                          binds=row["binds"], exercises_raw=row["exercises_raw"],
                          requirements=tuple(row["requirements"]),
                          breaks=row["breaks"], status=row["status"],
                          status_note=row["status_note"])
                 for row in rows)


# ---------------------------------------------------------------- §0.5 queries

def by_tier(scenarios, tier: str) -> tuple[Scenario, ...]:
    """"What must work at v1?" is `by_tier(scenarios, "P0")`."""
    return tuple(s for s in scenarios if s.tier == tier)


def by_variant(scenarios, variant: str) -> tuple[Scenario, ...]:
    return tuple(s for s in scenarios if s.variant == variant)


def citing(scenarios, requirement: str) -> tuple[Scenario, ...]:
    """"Which scenarios justify FR-15?" — the requirement's evidence."""
    return tuple(s for s in scenarios if requirement in s.requirements)


def operational(scenarios) -> tuple[Scenario, ...]:
    return tuple(s for s in scenarios if not s.is_pathological)


def pathological(scenarios) -> tuple[Scenario, ...]:
    return tuple(s for s in scenarios if s.is_pathological)


def declined(scenarios) -> tuple[Scenario, ...]:
    """"What should the engine decline?" — anything not fully modelled."""
    return tuple(s for s in scenarios if s.status != "MODELLED")


# ------------------------------------------------------- §13.6 coverage report

@dataclass(frozen=True)
class Coverage:
    """Requirements against the scenarios that justify them.

    §13.6 wants the matrix generated "so a requirement landing without a
    scenario is reported rather than passing unnoticed". Both directions are
    defects and they are different defects, so they are separate fields.
    """

    defined: frozenset[str]
    cited: frozenset[str]
    proposed: frozenset[str]

    @property
    def dangling(self) -> frozenset[str]:
        """Cited by an entry, defined nowhere. A broken cross-reference."""
        return self.cited - self.defined

    @property
    def unevidenced(self) -> frozenset[str]:
        """Defined in the spec, cited by no entry. A requirement with no
        operation behind it -- which may be correct, but must be a decision."""
        return self.defined - self.cited


def requirements_in_spec(path: Path | None = None) -> frozenset[str]:
    """The `FR-nn` identifiers §3 of the design document actually defines."""
    return frozenset(SPEC_REQUIREMENT.findall((path or SPEC).read_text()))


def coverage(scenarios, spec: Path | None = None) -> Coverage:
    """Cross-reference the catalogue against the design document.

    `FR-Pnn` are held apart rather than counted as dangling. §0.6 is explicit
    that they are proposals the catalogue introduced for needs the design
    document does not yet cover, so "a reader who greps `SDD-VRP-001` for one
    will not find it, which is correct".
    """
    cited = {r for s in scenarios for r in s.requirements}
    return Coverage(defined=requirements_in_spec(spec),
                    cited=frozenset(r for r in cited if not r.startswith("FR-P")),
                    proposed=frozenset(r for r in cited if r.startswith("FR-P")))
