#!/usr/bin/env python3
"""Tier 1 documentation: what the sources can state about themselves.

Thirteen documents, none of them authored. Each is read out of the thing it
describes -- the OpenAPI document the compiled gateway publishes, the settings
table it reads its environment through, the dataclasses the solver validates
against, the Makefile, the lockfiles -- so no document here can describe an
endpoint, a setting or a field that no longer exists.

That is the whole claim of Tier 1 and the reason these files are committed
rather than built on demand: a reader with no toolchain still gets them, and
`tests/test_tier1_docs.py` fails the suite when the committed copy stops
matching a fresh build. It is the contract
`test_the_generated_catalogue_matches_its_source` already holds
`docs/TDD/vrp-catalogue-v2.1.md` to.

Nothing here is a judgement. Anything that needs one -- why the architecture is
shaped this way, what the SLOs are, whether a gap matters -- belongs in a
written document, not in this build.

Run: `make tier1`. The gateway binary must be built first, because documents 01
and 02 come from a live `/openapi.json` rather than from a parse of the Rust.

An optional argument writes the set somewhere else, which is how the freshness
test builds a fresh copy without disturbing the committed one.
"""

from __future__ import annotations

import ast
import dataclasses
import json
import re
import sys
import tomllib
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any, NamedTuple

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]

BANNER = ("<!-- Generated by docs/tier1/build.py. Do not edit by hand; "
          "run `make tier1`. -->")

# Where the documents land. Replaced by `main` when an argument asks for it.
DESTINATION = HERE

# The trees that count as this system's own source, for the citation scan.
SOURCE_TREES = ("vrp", "tests", "examples/src", "examples/tools", "parity",
                "loadtest", "gateway/src", "rust-spike/src")

# The identifier families the code cites. Defined by the specification, but
# their use is in the code, which is what this scan reads.
IDENTIFIER = re.compile(
    r"\b(FR|NFR|T|CON|MTX|INV|DYN|AC|ALG|DEC|US|UC|E)-(\d{1,3}(?:\.\d+)?)\b")


class Doc(NamedTuple):
    """One generated document: where it lands and what it was read from."""

    slug: str
    title: str
    sources: tuple[str, ...]


def read(relative: str) -> str:
    """Read one repository file as text.

    Args:
        relative: Path relative to the repository root.

    Returns:
        The file's contents.
    """
    return (REPO / relative).read_text()


def relative(path: Path) -> str:
    """Render a path the way a document should cite it."""
    return path.relative_to(REPO).as_posix()


def cell(value: object) -> str:
    """Flatten a value onto a single markdown table cell."""
    return " ".join(str(value).split()).replace("|", r"\|")


def table(headers: Sequence[str], rows: Iterable[Sequence[object]]) -> list[str]:
    """Render a markdown table, or a placeholder when there are no rows."""
    body = [f"| {' | '.join(cell(value) for value in row)} |" for row in rows]
    if not body:
        return ["*(none)*", ""]
    head = f"| {' | '.join(headers)} |"
    rule = "|" + "|".join("---" for _ in headers) + "|"
    return [head, rule, *body, ""]


def paragraph(raw: str | None) -> list[str]:
    """A prose block, empty when the source carries no description."""
    return [raw.strip(), ""] if raw and raw.strip() else []


def first_line(raw: str | None) -> str:
    """The opening line of a docstring or description."""
    return (raw or "").strip().split("\n")[0]


def summary(raw: str | None) -> str:
    """The first sentence of a description, for an index column."""
    flat = " ".join((raw or "").split())
    head = flat.split(". ")[0]
    return head if len(head) <= 160 else head[:157] + "…"


def identifiers(raw: str) -> list[str]:
    """Every requirement identifier cited in a piece of text, deduplicated."""
    found = {f"{family}-{number}" for family, number in IDENTIFIER.findall(raw)}
    return sorted(found, key=sort_key)


def sort_key(identifier: str) -> tuple[str, float]:
    """Order identifiers by family, then numerically rather than as text."""
    family, _, number = identifier.partition("-")
    return family, float(number)


def sources_in(tree: str, suffix: str = ".py") -> list[Path]:
    """Every source file of one kind under a tree, in path order."""
    return sorted(path for path in (REPO / tree).rglob(f"*{suffix}")
                  if "__pycache__" not in path.parts)


def docstring_of(path: Path) -> str:
    """A module's docstring, or an empty string when it has none."""
    return ast.get_docstring(ast.parse(path.read_text())) or ""


def emit(slug: str, title: str, sources: Sequence[str],
         body: Sequence[str]) -> Doc:
    """Write one document and record what it came from.

    Args:
        slug: File name within `docs/tier1/`.
        title: Level-one heading.
        sources: Repository paths the content was read from.
        body: Markdown lines below the heading.

    Returns:
        The document's index entry.
    """
    derived = ", ".join(f"`{source}`" for source in sources)
    lines = [BANNER, "", f"# {title}", "", f"*Derived from {derived}.*", "",
             *body]
    (DESTINATION / slug).write_text("\n".join(lines).rstrip() + "\n")
    return Doc(slug, title, tuple(sources))


# ---------------------------------------------------------------------------
# 01 + 02: the OpenAPI document the running binary publishes
# ---------------------------------------------------------------------------

def openapi_document() -> dict[str, Any]:
    """Fetch `/openapi.json` from a freshly started gateway.

    Read from a live instance rather than parsed out of the Rust, because the
    document is generated by `utoipa` from the same structs that deserialise
    requests: a parse of the annotations would be a second implementation of
    the thing being documented.

    Returns:
        The parsed OpenAPI document.

    Raises:
        SystemExit: when the gateway binary has not been built.
    """
    # `tests/conftest_gateway` is the one place that knows how to run the
    # binary -- its path, its readiness probe, its teardown. Imported here
    # rather than reimplemented, for the reason the parity harness gives.
    sys.path.insert(0, str(REPO / "tests"))
    import conftest_gateway
    import httpx

    if not conftest_gateway.BINARY.exists():
        raise SystemExit(
            "the gateway binary is missing; run\n"
            "  cargo build --manifest-path gateway/Cargo.toml\n"
            "or `make tier1`, which builds it first")
    # No routing engine: the document is served from the type system, and
    # `/health` answers "degraded" rather than failing, so readiness resolves.
    with conftest_gateway.gateway("http://127.0.0.1:1") as url:
        return httpx.get(f"{url}/openapi.json", timeout=30).json()


def type_name(schema: dict[str, Any]) -> str:
    """Render a schema node as a readable type, linking references by name."""
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        return f"[`{name}`](02-schema-catalogue.md#{name.lower()})"
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return type_name(schema["allOf"][0])
    for key in ("oneOf", "anyOf"):
        if key in schema:
            return " or ".join(type_name(part) for part in schema[key])
    if schema.get("type") == "array":
        return f"array of {type_name(schema.get('items', {}))}"
    if "enum" in schema:
        return " \\| ".join(f"`{value}`" for value in schema["enum"])
    kind = schema.get("type", "any")
    if isinstance(kind, list):
        return " or ".join(f"`{part}`" for part in kind)
    return f"`{kind}`"


def operations(spec: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    """Every (method, path, operation) the document declares, in path order."""
    return [(method.upper(), path, operation)
            for path, methods in sorted(spec["paths"].items())
            for method, operation in sorted(methods.items())]


def _request_body(operation: dict[str, Any]) -> list[str]:
    """The request body line, when the operation takes one."""
    content = operation.get("requestBody", {}).get("content", {})
    schema = content.get("application/json", {}).get("schema", {})
    return [f"**Request body:** {type_name(schema)}", ""] if schema else []


def _parameters(operation: dict[str, Any]) -> list[str]:
    """The parameter table, when the operation declares parameters."""
    parameters = operation.get("parameters", [])
    if not parameters:
        return []
    rows = [(item["name"], item["in"], type_name(item.get("schema", {})),
             "yes" if item.get("required") else "no",
             item.get("description", ""))
            for item in parameters]
    return ["**Parameters:**", "",
            *table(["Name", "In", "Type", "Required", "Meaning"], rows)]


def _responses(operation: dict[str, Any]) -> list[str]:
    """The status table every operation carries."""
    rows = [(status, response.get("description", ""))
            for status, response in sorted(operation.get("responses", {}).items())]
    return ["**Responses:**", "", *table(["Status", "Meaning"], rows)]


def _endpoint(method: str, path: str, operation: dict[str, Any]) -> list[str]:
    """One endpoint section: purpose, body, parameters, statuses."""
    return [f"### {method} `{path}`", "",
            *paragraph(operation.get("summary")),
            *paragraph(operation.get("description")),
            *_request_body(operation), *_parameters(operation),
            *_responses(operation)]


def doc_api(spec: dict[str, Any]) -> Doc:
    """01: every endpoint the gateway serves, from its own OpenAPI document."""
    live = [item for item in operations(spec) if not item[2].get("deprecated")]
    old = [item for item in operations(spec) if item[2].get("deprecated")]
    body = [(f"**{spec['info']['title']}** version `{spec['info']['version']}`. "
            f"{spec['info']['description']}"), "",
            "## Tags", "",
            *table(["Tag", "Covers"],
                   [(tag["name"], tag.get("description", ""))
                    for tag in spec.get("tags", [])]),
            "## Endpoints", "",
            *table(["Method", "Path", "Operation", "Tag", "Summary"],
                   [(method, f"`{path}`", f"`{op['operationId']}`",
                     ", ".join(op.get("tags", [])), first_line(op.get("summary")))
                    for method, path, op in live]),
            "## Deprecated aliases", "",
            "The same handlers, mounted without the version prefix.", "",
            *table(["Method", "Path"],
                   [(method, f"`{path}`") for method, path, _ in old]),
            "## Endpoint detail", ""]
    for method, path, operation in live:
        body += _endpoint(method, path, operation)
    return emit("01-api-reference.md", "01 — HTTP API reference",
                ["gateway/src/openapi.rs", "gateway/src/handlers.rs",
                 "gateway/src/main.rs"], body)


def _properties(schema: dict[str, Any]) -> list[str]:
    """The field table of an object schema."""
    required = set(schema.get("required", []))
    rows = [(f"`{name}`", type_name(field),
             "yes" if name in required else "no",
             f"`{field['default']!r}`" if "default" in field else "",
             field.get("description", ""))
            for name, field in schema.get("properties", {}).items()]
    return table(["Field", "Type", "Required", "Default", "Meaning"], rows)


def _schema_section(name: str, schema: dict[str, Any]) -> list[str]:
    """One schema: its description, then its fields or its permitted values."""
    lines = [f"### {name}", "", *paragraph(schema.get("description"))]
    if "enum" in schema:
        return [*lines, "Permitted values: "
                + ", ".join(f"`{value}`" for value in schema["enum"]), ""]
    if "properties" in schema:
        return [*lines, *_properties(schema)]
    return [*lines, f"Type: {type_name(schema)}", ""]


def doc_schemas(spec: dict[str, Any]) -> Doc:
    """02: every request and response type, field by field."""
    schemas = spec["components"]["schemas"]
    body = [("Every type the gateway deserialises a request into or serialises "
            "a response from. Constraints checked in `validate()` rather than "
            "by the type are described in the annotation, not enforced by the "
            "schema."), "",
            "## Index", "",
            *table(["Schema", "Kind", "Summary"],
                   [(f"[`{name}`](#{name.lower()})",
                     "enum" if "enum" in schema else schema.get("type", "union"),
                     summary(schema.get("description")))
                    for name, schema in sorted(schemas.items())]),
            "## Detail", ""]
    for name, schema in sorted(schemas.items()):
        body += _schema_section(name, schema)
    return emit("02-schema-catalogue.md", "02 — Request and response schemas",
                ["gateway/src/models.rs", "gateway/src/vrp/solve.rs"], body)


# ---------------------------------------------------------------------------
# 03: what the gateway can fail with
# ---------------------------------------------------------------------------

def _enum_variants(block: str) -> list[tuple[str, str]]:
    """Pair each `ApiError` variant with the doc comment above it."""
    variants: list[tuple[str, str]] = []
    doc: list[str] = []
    for line in block.splitlines():
        stripped = line.strip()
        if stripped.startswith("///"):
            doc.append(stripped[3:].strip())
        elif re.match(r"^[A-Z]\w*", stripped):
            variants.append((re.match(r"^[A-Z]\w*", stripped).group(0),
                             " ".join(doc)))
            doc = []
    return variants


def _arm_detail(arm: str) -> str:
    """Describe the `detail` body one match arm produces."""
    literal = re.search(r'"detail":\s*"([^"]+)"', arm)
    if literal:
        return f'`"{literal.group(1)}"`'
    if "ValidationError" in arm:
        return "a list of validation errors"
    if "upstream_detail" in arm:
        return "the engine's `code` and `message`, or a bare string"
    return "a list of validation errors" if "errors" in arm else "(structured)"


def _arm_status(arm: str) -> str:
    """The status one match arm answers with."""
    if "from_u16" in arm:
        return "the engine's own, or `INTERNAL_SERVER_ERROR` if it sent no valid one"
    found = re.search(r"StatusCode::([A-Z_]+)", arm)
    return f"`{found.group(1)}`" if found else "—"


def _status_arms(impl: str) -> list[tuple[str, str, str]]:
    """Read (case, status, detail) out of `IntoResponse for ApiError`."""
    pattern = re.compile(r"ApiError::(\w+)(?:\(OsrmError::(\w+))?")
    marks = list(pattern.finditer(impl))
    arms = []
    for index, mark in enumerate(marks):
        end = marks[index + 1].start() if index + 1 < len(marks) else len(impl)
        arm = impl[mark.start():end]
        case = mark.group(1) + (f" / {mark.group(2)}" if mark.group(2) else "")
        arms.append((case, _arm_status(arm), _arm_detail(arm)))
    return arms


def _statuses_elsewhere() -> list[tuple[str, str, str]]:
    """Statuses the gateway returns without going through `ApiError`."""
    rows = []
    for path in sources_in("gateway/src", ".rs"):
        lines = path.read_text().splitlines()
        for number, line in enumerate(lines):
            found = re.search(r"StatusCode::([A-Z_]+)", line)
            if not found or "error.rs" in relative(path):
                continue
            context = next((earlier.strip() for earlier in
                            reversed(lines[:number]) if "fn " in earlier), "")
            rows.append((found.group(1), f"`{relative(path)}:{number + 1}`",
                         context.replace("{", "").strip()))
    return rows


def doc_errors() -> Doc:
    """03: the failure taxonomy, and the status each case answers with."""
    source = read("gateway/src/error.rs")
    enum = re.search(r"pub enum ApiError \{(.*?)\n\}", source, re.DOTALL).group(1)
    impl = re.search(r"match self \{(.*?)\n        \}", source, re.DOTALL).group(1)
    body = ["## Failure cases", "",
            *table(["Variant", "Raised when"], _enum_variants(enum)),
            "## What the client receives", "",
            *table(["Case", "Status", "`detail`"], _status_arms(impl)),
            "## Statuses produced outside `ApiError`", "",
            ("Rate limiting, the panic guard, readiness and the method "
            "fallback answer directly."), "",
            *table(["Status", "Site", "Function"], _statuses_elsewhere())]
    return emit("03-error-catalogue.md", "03 — Error catalogue",
                ["gateway/src/error.rs", "gateway/src/main.rs",
                 "gateway/src/handlers.rs"], body)


# ---------------------------------------------------------------------------
# 04: every setting, its default, and the value both deployments ship
# ---------------------------------------------------------------------------

SETTING = re.compile(
    r'^\s*(\w+)\s*:\s*([\w:<>, ]+?)\s*=\s*"([A-Z0-9_]+)"\s*/\s*"(.*)",\s*$')


def _settings_table() -> list[tuple[str, str, str, str, str]]:
    """Read the `settings!` declaration: section, name, type, default, notes."""
    block = re.search(r"settings! \{(.*?)\n\}", read("gateway/src/config.rs"),
                      re.DOTALL).group(1)
    section, doc, rows = "General", [], []
    for line in block.splitlines():
        heading = re.match(r"\s*// --- (.+?) ---", line)
        if heading:
            section = heading.group(1)
        elif line.strip().startswith("///"):
            doc.append(line.strip()[3:].strip())
        elif (found := SETTING.match(line)):
            _field, kind, name, default = found.groups()
            rows.append((section, name, kind, default, " ".join(doc)))
            doc = []
    return rows


def _app_env() -> dict[str, str]:
    """The values `deploy/env/app.env` ships to both deployments."""
    return dict(line.split("=", 1) for line in read("deploy/env/app.env").splitlines()
                if re.match(r"^[A-Z][A-Z0-9_]*=", line))


def _shipped_value(shipped: dict[str, str], name: str) -> str:
    """How `app.env` sets one setting, distinguishing unset from empty."""
    if name not in shipped:
        return "—"
    return f"`{shipped[name]}`" if shipped[name] else "*(empty)*"


def _undeclared_env() -> list[tuple[str, str]]:
    """Environment variables read outside the settings table."""
    declared = {name for _, name, _, _, _ in _settings_table()}
    found = set()
    for path in sources_in("gateway/src", ".rs"):
        for name in re.findall(r'env::var\("([A-Z][A-Z0-9_]*)"\)',
                               path.read_text()):
            if name not in declared:
                found.add((name, relative(path)))
    return sorted(found)


def _inert_settings() -> list[tuple[str, str]]:
    """Keys `app.env` carries that the gateway deliberately does not read."""
    block = re.search(r"INTENTIONALLY_UNUSED: &\[\(&str, &str\)\] = &\[(.*?)\];",
                      read("gateway/src/config.rs"), re.DOTALL)
    if not block:
        return []
    return [(f"`{name}`", reason) for name, reason in
            re.findall(r'\("([A-Z0-9_]+)",\s*"(.*?)"\)', block.group(1))]


def doc_config() -> Doc:
    """04: the settings surface, cross-checked against the shipped file."""
    shipped = _app_env()
    rows = [(f"`{name}`", section, f"`{kind}`",
             f"`{default}`" if default else "*(empty)*",
             _shipped_value(shipped, name),
             "yes" if shipped.get(name, default) == default else "**differs**")
            for section, name, kind, default, _notes in _settings_table()]
    detailed = [(f"`{name}`", notes)
                for _s, name, _k, _d, notes in _settings_table() if notes]
    body = [(f"{len(rows)} settings. Every one is read by name from the process "
            "environment, falls back to the committed default when unset or "
            "unparseable, and is matched case-insensitively."), "",
            "## Settings", "",
            *table(["Variable", "Group", "Type", "Default", "`app.env`",
                    "Agrees"], rows),
            "## Why a setting exists", "",
            *table(["Variable", "Note"], detailed),
            "## Read outside the settings table", "",
            *table(["Variable", "Site"], _undeclared_env()),
            "## Carried by `app.env` but deliberately not read", "",
            *table(["Variable", "Why not"], _inert_settings())]
    return emit("04-configuration-reference.md", "04 — Configuration reference",
                ["gateway/src/config.rs", "deploy/env/app.env"], body)


# ---------------------------------------------------------------------------
# 05: the domain model the solver and the verifier share
# ---------------------------------------------------------------------------

def _message(node: ast.expr) -> str:
    """Render a `_require` message, keeping f-string placeholders visible."""
    if isinstance(node, ast.Constant):
        return str(node.value)
    if isinstance(node, ast.JoinedStr):
        return "".join(part.value if isinstance(part, ast.Constant) else "{…}"
                       for part in node.values)
    return ""


def _constructor_rules() -> dict[str, list[str]]:
    """Every `_require` message, by the class whose constructor reports it."""
    rules: dict[str, list[str]] = {}
    for node in ast.parse(read("vrp/model.py")).body:
        if not isinstance(node, ast.ClassDef):
            continue
        messages = [_message(call.args[1]) for call in ast.walk(node)
                    if isinstance(call, ast.Call)
                    and getattr(call.func, "id", "") == "_require"
                    and len(call.args) > 1]
        rules[node.name] = sorted({message for message in messages if message})
    return rules


def _default(field: dataclasses.Field) -> str:
    """How a field is filled when the caller omits it."""
    if field.default is not dataclasses.MISSING:
        return f"`{field.default!r}`"
    if field.default_factory is not dataclasses.MISSING:
        return f"`{field.default_factory.__name__}()`"
    return "**required**"


def _entity(entity: type, rules: Sequence[str]) -> list[str]:
    """One domain type: what it is, its fields, and what it refuses."""
    lines = [f"### {entity.__name__}", "",
             *paragraph(entity.__doc__ if entity.__doc__
                        and not entity.__doc__.startswith(entity.__name__)
                        else None),
             *table(["Field", "Type", "Default"],
                    [(f"`{field.name}`", f"`{field.type}`", _default(field))
                     for field in dataclasses.fields(entity)])]
    if rules:
        lines += ["Refused on construction:", "",
                  *[f"- {rule}" for rule in rules], ""]
    return lines


def doc_domain() -> Doc:
    """05: the dataclasses every engine, verifier and adapter agrees on."""
    from vrp import model

    rules = _constructor_rules()
    entities = [value for value in vars(model).values()
                if isinstance(value, type) and dataclasses.is_dataclass(value)
                and value.__module__ == "vrp.model"]
    errors = [(f"`{value.__name__}`", f"`{value.__bases__[0].__name__}`",
               first_line(value.__doc__))
              for value in vars(model).values()
              if isinstance(value, type) and issubclass(value, Exception)
              and value.__module__ == "vrp.model"]
    body = [(f"{len(entities)} frozen dataclasses. Every one validates itself on "
            "construction, so an invalid instance cannot be built and no "
            "downstream stage has to re-check it."), "",
            "## Types", "",
            *table(["Type", "Fields"],
                   [(f"[`{entity.__name__}`](#{entity.__name__.lower()})",
                     len(dataclasses.fields(entity))) for entity in entities]),
            "## Errors", "", *table(["Exception", "Base", "Raised when"], errors),
            "## Detail", ""]
    for entity in entities:
        body += _entity(entity, rules.get(entity.__name__, []))
    return emit("05-domain-model.md", "05 — Domain model reference",
                ["vrp/model.py"], body)


# ---------------------------------------------------------------------------
# 06: the delivery-model file format, derived from the coverage contract
# ---------------------------------------------------------------------------

def _shipped_models(servicemodel: Any) -> list[tuple[str, ...]]:
    """Each shipped model, with the result of validating its keys.

    Asks `servicemodel.shipped()` rather than listing `models/`, because the
    directory also holds the category map, which is not a model and fails a
    model's validation for the uninteresting reason that it is a different file.
    """
    rows = []
    for name in servicemodel.shipped():
        raw = servicemodel.model_for(name)
        problems = servicemodel.validate_keys(raw)
        fleet = {str(entry.get("class")) for entry in raw.get("fleet", [])}
        rows.append((f"`{name}`", raw.get("problem_id", "—"),
                     raw.get("base", "—"), len(raw.get("applies_to", [])),
                     ", ".join(sorted(fleet)) or "—",
                     "valid" if not problems else "; ".join(problems)))
    return rows


def _categories(servicemodel: Any) -> tuple[list[tuple[str, str]], list[str]]:
    """The category map, and any shipped model no category can reach."""
    mapping = json.loads(read("models/categories.json"))
    rows = sorted((category, f"`{model}`") for category, model in mapping.items())
    return rows, servicemodel.unreachable(mapping)


def doc_delivery_models() -> Doc:
    """06: which domain fields a delivery model may set, and which it may not."""
    from vrp import servicemodel

    covered = sorted(((entity.__name__, field, key)
                      for entity, mapping in servicemodel.COVERS.items()
                      for field, key in mapping.items()),
                     key=lambda row: (row[0], row[2]))
    excluded = sorted((entity.__name__, field, reason)
                      for entity, mapping in servicemodel.EXCLUDES.items()
                      for field, reason in mapping.items())
    categories, orphans = _categories(servicemodel)
    body = [("A delivery model is an operation described as data: everything "
            "except today's demand. The key set below is *computed* from the "
            "coverage contract, so it cannot drift from the domain model."), "",
            "## Top-level keys", "",
            "Fields: " + ", ".join(f"`{key}`" for key in
                                   sorted(servicemodel.known_keys())) + ".", "",
            "Structural: " + ", ".join(f"`{key}`" for key in
                                       sorted(servicemodel.STRUCTURAL_KEYS))
            + ".", "",
            "## Model key to domain field", "",
            *table(["Domain type", "Field", "Model key"],
                   [(entity, f"`{field}`", f"`{key}`")
                    for entity, field, key in covered]),
            "## Deliberately not settable", "",
            *table(["Domain type", "Field", "Why not"],
                   [(entity, f"`{field}`", reason)
                    for entity, field, reason in excluded]),
            "## Shipped models", "",
            *table(["Model", "Problem", "Base", "Categories", "Fleet classes",
                    "Keys"], _shipped_models(servicemodel)),
            "## Item category to model", "",
            *table(["Category", "Served by"], categories),
            "Unreachable models: "
            + (", ".join(f"`{name}`" for name in orphans) if orphans
               else "none -- every shipped model is selectable.")]
    return emit("06-delivery-model-schema.md",
                "06 — Delivery model file format",
                ["vrp/servicemodel.py", "models/"], body)


# ---------------------------------------------------------------------------
# 07: what you can run
# ---------------------------------------------------------------------------

HELP_LINE = re.compile(r'^@echo "\s\s([a-z][\w/-]*)\s+-\s+(.+?)"$')
TARGET_LINE = re.compile(r"^([a-z][a-z0-9_-]*):(?!=)\s*([^#]*)(?:##\s*(.*))?$")
VARIABLE_LINE = re.compile(r"^([A-Z][A-Z0-9_]*)\s*\?=\s*(.*)$")


def _expand(described: dict[str, str]) -> dict[str, str]:
    """Split a combined help entry such as `jail-spike-up/-down` per target."""
    expanded: dict[str, str] = {}
    for key, description in described.items():
        names = key.split("/")
        stem = names[0].rsplit("-", 1)[0]
        for name in names:
            target = stem + name if name.startswith("-") else name
            expanded[target] = description
    return expanded


def doc_commands() -> Doc:
    """07: every make target, its prerequisites and its own description."""
    lines = read("Makefile").splitlines()
    described = _expand(dict(
        found.groups() for found in
        (HELP_LINE.match(line.strip()) for line in lines) if found))
    variables = [(f"`{found.group(1)}`", f"`{found.group(2)}`" if found.group(2)
                  else "*(empty)*")
                 for found in (VARIABLE_LINE.match(line) for line in lines)
                 if found]
    targets = []
    for found in (TARGET_LINE.match(line) for line in lines):
        if not found:
            continue
        name, needs, inline = found.groups()
        targets.append((f"`{name}`", " ".join((needs or "").split()) or "—",
                        (inline or described.get(name) or "—").strip()))
    body = [(f"{len(targets)} targets. The compose file is not at the repository "
            "root, so a bare `docker compose up` finds nothing: the targets are "
            "the interface."), "",
            "## Targets", "",
            *table(["Target", "Needs", "What it does"], targets),
            "## Variables you can override", "",
            *table(["Variable", "Default"], variables)]
    return emit("07-command-reference.md", "07 — Command reference",
                ["Makefile"], body)


# ---------------------------------------------------------------------------
# 08 to 11: what the repository contains
# ---------------------------------------------------------------------------

def _grouped(paths: Sequence[Path]) -> dict[str, list[Path]]:
    """Group source files by the directory that holds them."""
    groups: dict[str, list[Path]] = {}
    for path in paths:
        groups.setdefault(relative(path.parent), []).append(path)
    return groups


def doc_modules() -> Doc:
    """08: one line per module of the routing platform, from its docstring."""
    modules = sources_in("vrp")
    body = [(f"{len(modules)} modules, {sum(len(path.read_text().splitlines()) for path in modules):,} "
            "lines. Every module opens with what it is for and the "
            "requirements it implements; both columns are read from there."), ""]
    for directory, paths in sorted(_grouped(modules).items()):
        body += [f"## `{directory}/`", "",
                 *table(["Module", "Lines", "Purpose", "Implements"],
                        [(f"`{path.name}`",
                          len(path.read_text().splitlines()),
                          first_line(docstring_of(path)).split(" — ")[0],
                          ", ".join(identifiers(first_line(docstring_of(path))))
                          or "—")
                         for path in paths])]
    return emit("08-module-map.md", "08 — Routing platform module map",
                ["vrp/**/*.py"], body)


def _citations() -> dict[str, set[str]]:
    """Map every requirement identifier to the files that cite it."""
    hits: dict[str, set[str]] = {}
    for tree in SOURCE_TREES:
        for suffix in (".py", ".rs"):
            for path in sources_in(tree, suffix):
                for name in identifiers(path.read_text()):
                    hits.setdefault(name, set()).add(relative(path))
    return hits


def _citation_rows(hits: dict[str, set[str]], family: str) -> list[tuple]:
    """One family's identifiers, with where each is cited."""
    rows = []
    for name in sorted((key for key in hits if key.startswith(f"{family}-")),
                       key=sort_key):
        files = sorted(hits[name])
        shown = ", ".join(f"`{item}`" for item in files[:6])
        extra = f" +{len(files) - 6} more" if len(files) > 6 else ""
        rows.append((f"`{name}`", len(files), shown + extra))
    return rows


def doc_traceability() -> Doc:
    """09: which code claims which requirement, read from the code alone."""
    hits = _citations()
    families = sorted({name.partition("-")[0] for name in hits})
    body = [(f"{len(hits)} identifiers cited across {len(SOURCE_TREES)} source "
            "trees. This is the *code's* claim, not the specification's: an "
            "identifier appears here because a module, test or example names "
            "it."), "",
            *table(["Family", "Identifiers cited"],
                   [(f"`{family}-`", len([k for k in hits
                                          if k.startswith(f"{family}-")]))
                    for family in families])]
    for family in families:
        body += [f"## `{family}-`", "",
                 *table(["Identifier", "Citations", "Cited in"],
                        _citation_rows(hits, family))]
    return emit("09-traceability-matrix.md", "09 — Requirement traceability",
                [f"{tree}/**" for tree in SOURCE_TREES], body)


def _test_count(path: Path) -> int:
    """How many test functions one file defines."""
    return sum(1 for node in ast.walk(ast.parse(path.read_text()))
               if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef)
               and node.name.startswith("test_"))


def doc_tests() -> Doc:
    """10: the suite, file by file, with what each file claims to check."""
    files = [path for path in sources_in("tests")
             if path.name.startswith("test_")]
    rust = [(f"`{relative(path)}`", path.read_text().count("#[test]"))
            for path in sources_in("gateway/src", ".rs")
            if "#[test]" in path.read_text()]
    body = [(f"{len(files)} Python test files, "
            f"{sum(_test_count(path) for path in files):,} test functions, and "
            f"{sum(count for _, count in rust):,} Rust unit tests."), ""]
    for directory, paths in sorted(_grouped(files).items()):
        body += [f"## `{directory}/`", "",
                 *table(["File", "Tests", "What it checks"],
                        [(f"`{path.name}`", _test_count(path),
                          first_line(docstring_of(path))) for path in paths])]
    body += ["## Rust unit tests", "", *table(["File", "Tests"], rust)]
    return emit("10-test-inventory.md", "10 — Test inventory",
                ["tests/**/*.py", "gateway/src/**/*.rs"], body)


def doc_examples() -> Doc:
    """11: every runnable example and the scenario it demonstrates."""
    scripts = [path for path in sources_in("examples")
               if path.name != "__init__.py" and ".venv" not in path.parts]
    body = [(f"{len(scripts)} runnable scripts. `make examples` lists them "
            "interactively; `make examples-check` runs every one and fails when "
            "any stops working."), ""]
    for directory, paths in sorted(_grouped(scripts).items()):
        body += [f"## `{directory}/`", "",
                 *table(["Script", "Demonstrates"],
                        [(f"`{path.name}`", first_line(docstring_of(path)))
                         for path in paths])]
    return emit("11-example-catalogue.md", "11 — Example catalogue",
                ["examples/**/*.py"], body)


# ---------------------------------------------------------------------------
# 12 + 13: what it depends on, and how fast it was last measured
# ---------------------------------------------------------------------------

def _comments(raw: str, entry: re.Pattern[str]) -> dict[str, str]:
    """Attach each contiguous comment block to the entry written below it."""
    notes: dict[str, str] = {}
    buffer: list[str] = []
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            buffer.append(stripped.lstrip("#").strip())
        elif (found := entry.match(stripped)):
            if buffer:
                notes[found.group(1)] = " ".join(buffer)
            buffer = []
        elif not stripped:
            buffer = []
    return notes


def _locked(lockfile: str) -> dict[str, str]:
    """Resolved versions, by package name, from a TOML lockfile."""
    return {package["name"]: package["version"]
            for package in tomllib.loads(read(lockfile))["package"]}


def _rust_dependencies() -> list[tuple[str, ...]]:
    """The gateway's crates: requirement, resolved version and rationale."""
    manifest = tomllib.loads(read("gateway/Cargo.toml"))
    locked = _locked("gateway/Cargo.lock")
    notes = _comments(read("gateway/Cargo.toml"),
                      re.compile(r"^([a-z0-9_-]+)\s*="))
    rows = []
    for section in ("dependencies", "dev-dependencies"):
        for name, spec in sorted(manifest.get(section, {}).items()):
            wanted = spec if isinstance(spec, str) else spec.get("version", "")
            rows.append((f"`{name}`", section, f"`{wanted}`",
                         f"`{locked.get(name, '—')}`", notes.get(name, "")))
    return rows


def _python_dependencies() -> list[tuple[str, ...]]:
    """The tooling's packages: requirement, resolved version and rationale."""
    manifest = tomllib.loads(read("pyproject.toml"))["project"]
    locked = _locked("uv.lock")
    notes = _comments(read("pyproject.toml"), re.compile(r'^"([A-Za-z0-9_.-]+)'))
    groups = [("dependencies", manifest.get("dependencies", []))]
    groups += [(f"optional: {name}", items) for name, items
               in sorted(manifest.get("optional-dependencies", {}).items())]
    return [(f"`{re.split(r'[><=~!\[]', item)[0]}`", group, f"`{item}`",
             f"`{locked.get(re.split(r'[><=~!\[]', item)[0], '—')}`",
             notes.get(re.split(r"[><=~!\[]", item)[0], ""))
            for group, items in groups for item in items]


def doc_dependencies() -> Doc:
    """12: every declared dependency, with the reason the manifest gives."""
    body = [("Requirement, resolved version, and the rationale the manifest "
            "itself records. A blank reason means the manifest gives none."), "",
            "## Rust (`gateway/`)", "",
            *table(["Crate", "Group", "Requirement", "Resolved", "Why"],
                   _rust_dependencies()),
            "## Python (tooling, tests, examples)", "",
            *table(["Package", "Group", "Requirement", "Resolved", "Why"],
                   _python_dependencies())]
    return emit("12-dependency-inventory.md", "12 — Dependency inventory",
                ["gateway/Cargo.toml", "gateway/Cargo.lock", "pyproject.toml",
                 "uv.lock"], body)


def doc_baseline() -> Doc:
    """13: the recorded solver baseline and the instances behind it."""
    baseline = json.loads(read("benchmarks/baseline.json"))
    instances = sorted((REPO / "benchmarks/instances").iterdir())
    metadata = [(f"`{key}`", value) for key, value in baseline.items()
                if not isinstance(value, list)]
    body = [("The committed reference the regression gate compares against. "
            "Numbers are what the recorded run produced, not targets."), "",
            "## Run", "", *table(["Field", "Value"], metadata),
            "## Instances solved", "",
            *table(["Instance", "Cost", "Distance", "Vehicles", "Verified"],
                   [(entry["name"], f"{entry['cost']:,}",
                     f"{entry['distance']:,}", entry["vehicles"],
                     "yes" if entry["verified"] else "no")
                    for entry in baseline["instances"]]),
            "## Published instance files", "",
            *table(["File", "Bytes"],
                   [(f"`{relative(path)}`", f"{path.stat().st_size:,}")
                    for path in instances if path.is_file()])]
    return emit("13-benchmark-baseline.md", "13 — Benchmark baseline",
                ["benchmarks/baseline.json", "benchmarks/instances/"], body)


# ---------------------------------------------------------------------------
# The index, and the run
# ---------------------------------------------------------------------------

def index(docs: Sequence[Doc]) -> Doc:
    """Write the folder's own README: what Tier 1 is and how to rebuild it."""
    body = [("**Tier 1 is documentation the sources can state about "
            "themselves.** Nothing here was written by hand and nothing here "
            "carries a judgement: every table is read from the code, the "
            "manifests, the Makefile or the binary's own OpenAPI document."), "",
            ("Do not edit these files. `make tier1` is the only writer, and "
            "`tests/test_tier1_docs.py` fails when a committed copy stops "
            "matching a fresh build."), "",
            *table(["Document", "Derived from"],
                   [(f"[{doc.title}]({doc.slug})",
                     ", ".join(f"`{source}`" for source in doc.sources))
                    for doc in docs]),
            "## Rebuilding", "",
            "```sh", "make tier1", "```", "",
            ("Documents 01 and 02 are fetched from a gateway started for the "
            "purpose, so the target builds the binary first. Everything else "
            "reads the working tree.")]
    return emit("README.md", "Tier 1 — generated documentation",
                ["docs/tier1/build.py"], body)


def main(argv: Sequence[str]) -> int:
    """Generate every Tier 1 document.

    Args:
        argv: An optional destination directory, defaulting to this folder.

    Returns:
        A process exit code.
    """
    global DESTINATION
    if argv:
        DESTINATION = Path(argv[0]).resolve()
        DESTINATION.mkdir(parents=True, exist_ok=True)
    sys.path.insert(0, str(REPO))
    spec = openapi_document()
    docs = [doc_api(spec), doc_schemas(spec), doc_errors(), doc_config(),
            doc_domain(), doc_delivery_models(), doc_commands(), doc_modules(),
            doc_traceability(), doc_tests(), doc_examples(),
            doc_dependencies(), doc_baseline()]
    docs.append(index(docs))
    for doc in docs:
        print(f"wrote {DESTINATION.name}/{doc.slug}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
