"""Learning the traffic from what the vans actually did.

Demonstrates speed-profile calibration landed for E-63/T-63 (§12.2):

    vrp.speedfit   grouped medians of observed speed, per road class and hour

§12.2: "Fit per-arc-class, per-bucket speed multipliers from observed GPS
traces against the routing engine's free-flow assumptions. Maintain FIFO by
construction (§6.3). Re-fit weekly; hold out one week for validation."

`T-40` built the construction that consumes a profile and `T-82` taught the
search to plan under one. Both used profiles somebody invented. This is where
the numbers come from instead.

Five things, in order:

1. **The raw material.** An executed route is a list of arrivals and
   departures. Between two stops it says how long the road took; the matrix
   says how long the engine thought it would. The ratio is the multiplier.

2. **What has to be thrown away.** An arc that crossed the top of the hour was
   driven at two speeds and reports one duration. It is excluded and counted,
   because attributing it to the hour it left in produces a plausible number
   that is wrong.

3. **The fit, and whether it worked.** Traces are generated by driving a known
   profile, so the recovered multipliers can be checked against the traffic
   that produced them. Against real telematics nobody can do that, which is
   why the held-out week exists.

4. **The held-out week.** A fit always explains its own data. §12.2 holds a
   week back, and the report has to be capable of saying no -- shown by
   scoring the same fit against a week of traffic it never saw.

5. **What the fit is not allowed to do.** §12.2 fits per arc class; the model
   carries one profile per instance. The classes stay apart rather than being
   averaged into a profile that describes no road in particular.

Requires a running gateway: distances are measured on the road network and
there is no straight-line fallback. `examples/.env` points at the FreeBSD jail. The traces are generated; §12.2 against real telematics needs
volume this stack does not have, and that is a data question rather than an
engineering one.

Usage:
    uv run --package osrm-api-gateway-examples \\
        examples/src/fleet/learn/speed_calibration.py
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "examples" / "src"))

# Importing config puts OSRM_API_URL into the environment, so the
# gateway this example now requires is the one `examples/.env` names.
import config  # noqa: F401
import dataset

from vrp.adherence import ExecutedRoute
from vrp.model import (
    Order,
    Problem,
    StopSpec,
    TimeWindow,
    Vehicle,
)
from vrp.speedfit import ArcKey, fit, recalibrate, traversals, validate
from vrp.timedependent import SpeedProfile, travel

HOUR = 3600
DAY = 24 * HOUR
RUSH = (8, 9, 10)


def real_traffic() -> SpeedProfile:
    """The traffic the town actually has, which nobody has told the planner."""
    return SpeedProfile(
        bucket_seconds=HOUR,
        multipliers_ppt=tuple(
            500 if hour in RUSH else 750 if 17 <= hour <= 18 else 1000
            for hour in range(24)))


def a_town(stops: int = 8, slice_: str = "spread") -> Problem:
    """Real deliveries around the Guadalupe depot, priced at free flow.

    `spread` walks a real catchment: consecutive hops run from nine seconds to
    a quarter of an hour, all of them comfortably inside an hourly bucket,
    which is the ordinary case a calibration learns from. `furthest` gives the
    rural round -- legs of hours -- and section 2 uses it to show what a
    bucket-straddling arc costs you.

    The matrix is the engine's free-flow guess. What the vans did against it is
    generated by driving a known profile, because that is the only way the fit
    can be checked at all.
    """
    locations, matrix, deliveries, _depot = dataset.road_sites(
        stops, strategy=slice_, name="freeflow")
    day = TimeWindow(start=0, end=DAY - 1)
    orders = tuple(
        Order(id=f"O{i + 1}", kind="JOB", quantities={"kg": d["units"]},
              delivery=StopSpec(location_id=f"C{i + 1}",
                                service_fixed=d["service_minutes"] * 60,
                                time_windows=(day,)))
        for i, d in enumerate(deliveries))
    return Problem(
        id="town", locations=locations, orders=orders,
        vehicles=(Vehicle(id="V1", capacities={"kg": 1000},
                          shift=TimeWindow(start=0, end=DAY - 1),
                          start_location_id="D", end_location_id="D"),),
        matrix=matrix)


def drive(problem: Problem, profile: SpeedProfile, sequence: list[str],
          start: int, service: int = 120) -> ExecutedRoute:
    """What the tracker in the cab would have reported."""
    index = {loc.id: loc.matrix_index for loc in problem.locations}
    arrivals: dict[str, int] = {}
    departures: dict[str, int] = {}
    here, clock = index["D"], start
    for order_id in sequence:
        there = index[problem.order(order_id).delivery.location_id]
        clock += travel(problem.matrix.duration(here, there), clock, profile)
        arrivals[order_id] = clock
        clock += service
        departures[order_id] = clock
        here = there
    return ExecutedRoute(
        vehicle_id="V1", driver_id="dave", depot_id="D", territory="north",
        sequence=tuple(sequence), arrivals=arrivals, departures=departures)


def a_week(problem: Problem, profile: SpeedProfile) -> list[ExecutedRoute]:
    sequence = [f"O{i}" for i in range(1, 9)]
    return [drive(problem, profile, sequence, hour * HOUR + day * 37)
            for day in range(5)
            for hour in (7, 8, 9, 10, 11, 14, 17, 18, 19)]


def clock(seconds: int) -> str:
    return f"{seconds // 3600 % 24:02d}:{seconds % 3600 // 60:02d}"


def heading(number: str, title: str) -> None:
    print(f"\n{'=' * 72}\n{number}  {title}\n{'=' * 72}")


def the_raw_material(problem: Problem, week: list[ExecutedRoute]) -> None:
    heading("1.", "What a tracker gives you, and what the engine believed")
    seen = traversals(problem, week, HOUR)
    print("\n   six arcs from the week, as driven:\n")
    print(f"      {'left':>6s} {'arc':>12s} {'engine':>8s} {'road':>8s} "
          f"{'speed':>8s}")
    for traversal in seen.kept[:3] + seen.kept[-3:]:
        print(f"      {clock(traversal.departed):>6s} "
              f"{traversal.origin_id + '->' + traversal.destination_id:>12s} "
              f"{traversal.free_flow_seconds:6d}s "
              f"{traversal.observed_seconds:6d}s "
              f"{traversal.multiplier_ppt:6d}ppt")
    print("\n   1000ppt is the engine being right. Anything less is traffic it")
    print("   did not know about.")


def what_is_discarded(problem: Problem) -> None:
    heading("2.", "The arcs that cannot be used, and why")
    for slice_, label in (("spread", "a city catchment"),
                          ("furthest", "a rural round")):
        town = a_town(slice_=slice_)
        seen = traversals(town, a_week(town, real_traffic()), HOUR)
        total = len(seen.kept) + seen.straddled
        print(f"\n   {label}: {len(seen.kept)} usable, {seen.straddled} "
              f"crossed the hour ({seen.straddled * 100 // total}%)")
    print("\n   A city round loses one arc in eight; a rural one loses half.")
    print("   A leg of an hour leaving at 08:40 spends twenty minutes in the")
    print("   peak and forty out of it: it reports one duration and attests to")
    print("   neither hour, so it is counted rather than guessed. Which is")
    print("   also to say a rural fleet needs more days of traces than an")
    print("   urban one to learn the same profile.")


def the_fit(problem: Problem, week: list[ExecutedRoute]) -> None:
    heading("3.", "The fit, against the traffic that produced it")
    calibration = fit(traversals(problem, week, HOUR), minimum=3,
                      bucket_seconds=HOUR, buckets=24)
    truth = real_traffic()
    fitted = calibration.profile("local")
    print("\n      hour   fitted     real   seen")
    for hour in (7, 8, 9, 10, 11, 14, 17, 18, 19):
        count = sum(1 for t in traversals(problem, week, HOUR).kept
                    if t.key == ArcKey("local", hour))
        print(f"      {hour:02d}:00 {fitted.multipliers_ppt[hour]:6d}ppt "
              f"{truth.multipliers_ppt[hour]:6d}ppt {count:5d}")
    defaulted = calibration.defaulted("local")
    print(f"\n   {len(defaulted)} hours nobody drove in, left at free flow:")
    print(f"      {', '.join(f'{h:02d}:00' for h in defaulted[:8])}, ...")
    print("   Free flow is the engine's own assumption, so defaulting changes")
    print("   nothing -- but which hours were defaulted is reported, or a")
    print("   profile fitted from two hours looks like one fitted from a day.")


def the_held_out_week(problem: Problem) -> None:
    heading("4.", "The week that was held back, and a week of something else")
    truth = real_traffic()
    weeks = [a_week(problem, truth) for _ in range(3)]
    calibration, report = recalibrate(problem, weeks, minimum=3,
                                      bucket_seconds=HOUR, buckets=24)
    gridlock = SpeedProfile(bucket_seconds=HOUR, multipliers_ppt=(200,) * 24)
    strange = validate(calibration, traversals(problem,
                                               a_week(problem, gridlock), HOUR))
    print(f"\n      {'held-out week':22s} {'arcs':>6s} {'median':>8s} "
          f"{'worst':>7s}")
    for label, result in (("traffic it learned", report),
                          ("a day of gridlock", strange)):
        print(f"      {label:22s} {result.arcs:6d} "
              f"{result.median_error_seconds:6d}s {result.worst_error_seconds:6d}s")
    print("\n   A report that cannot score badly is not a validation. The")
    print("   second row is what a week the fit does not describe looks like.")


def what_it_refuses(problem: Problem) -> None:
    heading("5.", "The one thing the fit will not do")
    calibration = fit(traversals(problem, a_week(problem, real_traffic()), HOUR),
                      minimum=3, bucket_seconds=HOUR, buckets=24)
    print(f"\n   classes with observations: {calibration.classes}")
    try:
        calibration.profile("trunk")
    except KeyError as refusal:
        print(f"   asking for a class nobody drove:\n      {refusal.args[0]}")
    print("\n   §12.2 fits per arc class; Problem.speed_profile carries one")
    print("   profile for the whole instance and §6.3 asks for one per arc.")
    print("   Averaging the classes would produce a profile describing no road")
    print("   in particular, which is the failure this pipeline exists to")
    print("   prevent. Closing that gap in the model is T-83.")


def main() -> int:
    print(__doc__.strip().split("\n")[0])
    print("\n§12.2. The traces are generated, so the fit can be checked "
          "against the truth.")
    problem = a_town()
    week = a_week(problem, real_traffic())
    the_raw_material(problem, week)
    what_is_discarded(problem)
    the_fit(problem, week)
    the_held_out_week(problem)
    what_it_refuses(problem)
    print(f"\n{'=' * 72}")
    print("A profile somebody invented is a guess with arithmetic around it.")
    print("This is where the numbers come from.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
