"""Speed-profile calibration — §12.2, T-63.

§12.2: "Fit per-arc-class, per-bucket speed multipliers from observed GPS
traces against the routing engine's free-flow assumptions. Maintain FIFO by
construction (§6.3). Re-fit weekly; hold out one week for validation."

The traces here are generated by driving a known profile, which is the only way
to ask the question that matters: does the fit recover the traffic it was shown?
Against real telematics nobody knows the answer, so nobody can tell a working
pipeline from one that returns free flow every week.
"""

from __future__ import annotations

import pytest

from vrp.adherence import ExecutedRoute
from vrp.model import (
    Location,
    Order,
    Problem,
    StopSpec,
    TimeWindow,
    TravelMatrix,
    Vehicle,
)
from vrp.speedfit import (
    FREE_FLOW_PPT,
    ArcKey,
    fit,
    recalibrate,
    traversals,
    validate,
)
from vrp.timedependent import SpeedProfile, travel

HOUR = 3600
DAY = 24 * HOUR


def peak() -> SpeedProfile:
    """Half speed 08:00-10:59, three-quarters 17:00-18:59, free flow between."""
    return SpeedProfile(
        bucket_seconds=HOUR,
        multipliers_ppt=tuple(
            500 if 8 <= hour <= 10 else 750 if 17 <= hour <= 18 else 1000
            for hour in range(24)))


def a_town(stops: int = 8, hop: int = 240) -> Problem:
    """Stops on a road, priced at free flow. `hop` seconds between neighbours.

    Short hops on purpose: an arc has to fit inside a bucket to say anything
    about that bucket's speed, and a four-minute arc inside a one-hour bucket
    is the ordinary case rather than a convenience.
    """
    day = TimeWindow(start=0, end=DAY - 1)
    locations = tuple(
        Location(id="D" if i == 0 else f"C{i}", lat=9.9 + i / 200, lon=-84.0,
                 matrix_index=i)
        for i in range(stops + 1))
    grid = tuple(tuple(abs(i - j) * hop for j in range(stops + 1))
                 for i in range(stops + 1))
    orders = tuple(
        Order(id=f"O{i}", kind="JOB", quantities={"kg": 1},
              delivery=StopSpec(location_id=f"C{i}", service_fixed=120,
                                time_windows=(day,)))
        for i in range(1, stops + 1))
    return Problem(
        id="town", locations=locations, orders=orders,
        vehicles=(Vehicle(id="V1", capacities={"kg": 100},
                          shift=TimeWindow(start=0, end=DAY - 1),
                          start_location_id="D", end_location_id="D"),),
        matrix=TravelMatrix(version="freeflow", durations=grid, distances=grid))


def drive(problem: Problem, profile: SpeedProfile, sequence: list[str],
          start: int, service: int = 120) -> ExecutedRoute:
    """What telematics would report from a van that drove `profile`.

    The arrivals and departures are the ground truth the fit has to recover;
    the problem's matrix is the engine's free-flow guess, which is what §12.2
    means by fitting "against the routing engine's assumptions".
    """
    index = {loc.id: loc.matrix_index for loc in problem.locations}
    arrivals: dict[str, int] = {}
    departures: dict[str, int] = {}
    here = index["D"]
    clock = start
    for order_id in sequence:
        there = index[problem.order(order_id).delivery.location_id]
        clock += travel(problem.matrix.duration(here, there), clock, profile)
        arrivals[order_id] = clock
        clock += service
        departures[order_id] = clock
        here = there
    return ExecutedRoute(
        vehicle_id="V1", driver_id="dave", depot_id="D", territory="north",
        sequence=tuple(sequence), arrivals=arrivals, departures=departures)


def a_week(problem: Problem, profile: SpeedProfile,
           departures: tuple[int, ...] = (7, 8, 9, 10, 11, 14, 17, 18, 19)
           ) -> list[ExecutedRoute]:
    """One route per departure hour, five days running.

    Spread across the day on purpose: a bucket with no traffic in it cannot be
    fitted, and a week that only ever leaves at 08:00 knows nothing about 17:00.
    """
    sequence = [f"O{i}" for i in range(1, 9)]
    return [drive(problem, profile, sequence, hour * HOUR + day * 37)
            for day in range(5) for hour in departures]


# --------------------------------------------------------------------------
# The fit
# --------------------------------------------------------------------------

def test_a_fit_recovers_the_profile_the_traces_were_driven_under():
    """The one question a calibration pipeline has to answer.

    Every bucket the week actually drove in must come back at the multiplier
    that produced it. A pipeline that returned free flow everywhere would pass
    any test that only checked the output was a valid profile.
    """
    problem, truth = a_town(), peak()
    seen = traversals(problem, a_week(problem, truth), HOUR)
    calibration = fit(seen, minimum=3, bucket_seconds=HOUR, buckets=24)

    fitted = calibration.profile("local")
    driven = {8, 9, 10, 17, 18, 7, 11, 14, 19}
    for bucket in sorted(driven):
        assert abs(fitted.multipliers_ppt[bucket]
                   - truth.multipliers_ppt[bucket]) <= 5, (
            f"bucket {bucket:02d}:00 fitted at "
            f"{fitted.multipliers_ppt[bucket]}ppt, drove at "
            f"{truth.multipliers_ppt[bucket]}ppt")

    congested = [b for b in driven if truth.multipliers_ppt[b] < FREE_FLOW_PPT]
    assert congested, "no congested bucket was driven, so nothing was recovered"


def test_a_bucket_nobody_drove_in_is_free_flow_and_says_so():
    """An unfitted bucket must not be invented.

    Free flow is the honest default -- it is the engine's own assumption, so
    defaulting changes nothing -- but which buckets were defaulted has to be
    reportable, or a profile fitted from one hour of traffic looks like a
    profile fitted from a day of it.
    """
    problem, truth = a_town(), peak()
    week = a_week(problem, truth, departures=(8, 9))
    calibration = fit(traversals(problem, week, HOUR), minimum=3,
                      bucket_seconds=HOUR, buckets=24)

    defaulted = calibration.defaulted("local")
    assert 3 in defaulted and 22 in defaulted
    assert 8 not in defaulted and 9 not in defaulted
    assert calibration.profile("local").multipliers_ppt[3] == FREE_FLOW_PPT


def test_a_thin_group_is_reported_rather_than_fitted():
    """One traversal is not evidence about an hour of traffic."""
    problem, truth = a_town(), peak()
    week = a_week(problem, truth, departures=(8,))[:1]
    calibration = fit(traversals(problem, week, HOUR), minimum=20,
                      bucket_seconds=HOUR, buckets=24)

    assert calibration.thin, "nothing was thin, so the minimum did no work"
    assert not calibration.by_key, "a group below the minimum was fitted anyway"
    assert all(count < 20 for count in calibration.thin.values())


def test_an_arc_that_crosses_a_bucket_boundary_is_excluded_and_counted():
    """A straddling arc drove through two speeds and attests to neither.

    Attributing it to the bucket it left in is the quiet version of the error:
    the number is plausible, wrong, and indistinguishable from a real one.
    """
    problem = a_town(hop=2400)  # forty minutes: straddles more often than not
    week = a_week(problem, peak())
    seen = traversals(problem, week, HOUR)

    assert seen.straddled > 0, (
        "no arc crossed a boundary, so this instance cannot tell exclusion "
        "from inclusion")
    assert all(t.observed_seconds + (t.departed % HOUR) <= HOUR
               for t in seen.kept), "a straddling arc was kept"


def test_a_traversal_faster_than_the_engine_believed_is_kept():
    """A multiplier above free flow is a finding, not a fault.

    The engine's free-flow number is an assumption; an arc that beats it says
    the assumption is pessimistic on that road. Clamping it at 1000 would hide
    exactly the class of error §12.2 exists to measure.
    """
    problem = a_town()
    quick = SpeedProfile(bucket_seconds=HOUR, multipliers_ppt=(2000,) * 24)
    calibration = fit(traversals(problem, a_week(problem, quick), HOUR),
                      minimum=3, bucket_seconds=HOUR, buckets=24)

    fitted = calibration.profile("local")
    assert fitted.multipliers_ppt[8] > FREE_FLOW_PPT


# --------------------------------------------------------------------------
# FIFO by construction
# --------------------------------------------------------------------------

def test_a_fitted_profile_is_fifo_whatever_the_traces_said():
    """§12.2's "maintain FIFO by construction".

    Not a property of the data. Two stops in the same yard are three seconds
    apart by the matrix; a van that sat there for an hour implies a multiplier
    of three thousandths of one, which integer division takes to zero, and
    `SpeedProfile` refuses a zero as an unreachable road rather than slow
    traffic. The fit floors it and leaves it visible: a number an operator can
    see is absurd beats a pipeline that raises at 03:00 on a Sunday.

    The arc has to be short enough to stay inside its bucket, or it is excluded
    as a straddler and the floor is never reached -- which is what this test
    checked before it was made to fail.
    """
    problem = a_town(stops=3, hop=3)
    stalled = ExecutedRoute(
        vehicle_id="V1", driver_id="dave", depot_id="D", territory="north",
        sequence=("O1", "O2"),
        arrivals={"O1": 8 * HOUR - 600, "O2": 8 * HOUR + 3500},
        departures={"O1": 8 * HOUR, "O2": 8 * HOUR + 3600})
    seen = traversals(problem, [stalled], HOUR)

    assert seen.kept, "the stalled arc was dropped, so no multiplier was floored"
    assert seen.kept[0].free_flow_seconds * FREE_FLOW_PPT \
        // seen.kept[0].observed_seconds == 0, (
        "this arc does not round to a zero multiplier, so it cannot show the "
        "floor doing anything")
    assert seen.kept[0].multiplier_ppt > 0

    calibration = fit(seen, minimum=1, bucket_seconds=HOUR, buckets=24)
    fitted = calibration.profile("local")
    assert all(m > 0 for m in fitted.multipliers_ppt)

    later, earlier = 8 * HOUR + 600, 8 * HOUR
    assert travel(3, later, fitted) + later >= travel(3, earlier, fitted) + earlier


# --------------------------------------------------------------------------
# Held-out validation
# --------------------------------------------------------------------------

def test_the_held_out_week_reports_error_against_what_actually_happened():
    """§12.2 holds out a week because a fit always explains its own data."""
    problem, truth = a_town(), peak()
    weeks = [a_week(problem, truth) for _ in range(3)]
    calibration, report = recalibrate(problem, weeks, minimum=3,
                                      bucket_seconds=HOUR, buckets=24)

    assert report.arcs > 0
    assert report.median_error_seconds <= 2, (
        "the held-out week was driven under the same profile that was fitted, "
        "so predictions should be nearly exact")
    assert calibration.by_key


def test_validation_notices_when_the_held_out_week_drove_different_traffic():
    """The report has to be capable of saying no.

    Validated only against a week like the one it learned, a report that always
    printed "median error 0" would be indistinguishable from a working one.
    """
    problem = a_town()
    learned = fit(traversals(problem, a_week(problem, peak()), HOUR),
                  minimum=3, bucket_seconds=HOUR, buckets=24)

    familiar = validate(learned, traversals(problem, a_week(problem, peak()),
                                            HOUR))
    gridlock = SpeedProfile(bucket_seconds=HOUR, multipliers_ppt=(200,) * 24)
    strange = validate(learned, traversals(problem, a_week(problem, gridlock),
                                           HOUR))

    assert strange.median_error_seconds > familiar.median_error_seconds * 4, (
        f"a week of gridlock scored {strange.median_error_seconds}s against "
        f"{familiar.median_error_seconds}s for a familiar one; the report "
        "cannot tell them apart")


def test_an_arc_class_the_fit_never_saw_is_counted_rather_than_guessed():
    """Scoring an unfitted arc against the engine's own guess would make a
    pipeline that fitted nothing look accurate on the roads it knows least."""
    problem, truth = a_town(), peak()
    learned = fit(traversals(problem, a_week(problem, truth), HOUR),
                  minimum=3, bucket_seconds=HOUR, buckets=24)
    assert learned.classes == ("local",), (
        "the training week already covers more than one class, so an unfitted "
        "class cannot be demonstrated")

    skipping = [drive(problem, truth, ["O1", "O3", "O5", "O7"], hour * HOUR)
                for hour in (8, 9, 10)]
    longer = traversals(problem, skipping, HOUR)
    assert {t.key.arc_class for t in longer.kept} == {"arterial"}, (
        "the held-out week is the same class as the training one")

    report = validate(learned, longer)
    assert report.unfitted_arcs == len(longer.kept)
    assert report.arcs == 0
    assert report.median_error_seconds == 0, (
        "an unfitted arc must contribute no error rather than a flattering one")


def test_a_weekly_refit_holds_out_the_most_recent_week():
    """"Re-fit weekly; hold out one week" -- the held-out week is not fitted."""
    problem, truth = a_town(), peak()
    gridlock = SpeedProfile(bucket_seconds=HOUR, multipliers_ppt=(200,) * 24)
    weeks = [a_week(problem, truth), a_week(problem, truth),
             a_week(problem, gridlock)]

    calibration, report = recalibrate(problem, weeks, minimum=3,
                                      bucket_seconds=HOUR, buckets=24)
    trained_on_all = fit(
        traversals(problem, [r for week in weeks for r in week], HOUR),
        minimum=3, bucket_seconds=HOUR, buckets=24)
    assert trained_on_all.by_key != calibration.by_key, (
        "the last week is indistinguishable from the others, so training on "
        "it would change nothing and this test could not tell")

    assert calibration.by_key == fit(
        traversals(problem, [r for week in weeks[:-1] for r in week], HOUR),
        minimum=3, bucket_seconds=HOUR, buckets=24).by_key, (
        "the held-out week changed the fit, so it was trained on")
    assert report.arcs > 0


def test_a_pipeline_with_one_week_cannot_validate_and_refuses_to_pretend():
    """Nothing to hold out is not a passing validation report."""
    problem = a_town()
    with pytest.raises(ValueError, match="held out"):
        recalibrate(problem, [a_week(problem, peak())], minimum=3,
                    bucket_seconds=HOUR, buckets=24)


# --------------------------------------------------------------------------
# What the model cannot carry
# --------------------------------------------------------------------------

def test_arc_classes_are_fitted_apart_and_never_averaged_together():
    """§12.2 fits per arc class; §6.3 stores a profile per arc.

    `Problem.speed_profile` carries one profile for a whole instance, so there
    is nowhere to put a per-class fit. The calibration keeps the classes apart
    and makes the caller name one, rather than collapsing them into a single
    profile that describes no road in particular.
    """
    problem = a_town()
    mixed = fit(traversals(problem, a_week(problem, peak()), HOUR),
                minimum=3, bucket_seconds=HOUR, buckets=24)

    assert all(isinstance(key, ArcKey) for key in mixed.by_key)
    with pytest.raises(KeyError, match="motorway"):
        mixed.profile("motorway")
