//! The OpenAPI document, generated from the types that serve the requests.
//!
//! This replaced a snapshot of FastAPI's generated schema, committed to the
//! repo and embedded at build time. That was correct while the pydantic models
//! were the only description of the API, but it tied the schema to an
//! implementation that no longer serves traffic: the file could only be
//! regenerated by running the FastAPI app.
//!
//! Generating here means the document comes from the same structs that
//! deserialise requests and serialise responses, so an endpoint cannot change
//! shape without the schema following. The cost is that constraints enforced in
//! `validate()` rather than in the type -- coordinate ranges, list lengths --
//! are described by hand in the annotations below and can drift; `tests/` holds
//! the checks that catch that.

use utoipa::openapi::security::SecurityScheme;
use utoipa::{Modify, OpenApi};

use crate::handlers;
use crate::models;
use crate::vrp::solve;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "OSRM API Gateway",
        description = "A gateway in front of osrm-routed, adding caching, rate \
                       limiting, request validation and vehicle-routing.",
        version = env!("CARGO_PKG_VERSION"),
    ),
    paths(
        handlers::route,
        handlers::matrix,
        handlers::matrix_graph,
        handlers::match_trace,
        handlers::trip,
        handlers::nearest,
        handlers::tile,
        handlers::vrp,
        handlers::vrp_allocate,
        handlers::health,
        handlers::ready,
        handlers::metrics,
    ),
    components(schemas(
        models::Coordinate,
        models::Stop,
        models::GpsBreadcrumb,
        models::RouteRequest,
        models::MatrixRequest,
        models::MatchRequest,
        models::TripRequest,
        models::NearestRequest,
        models::VrpRequest,
        models::ValidationError,
        solve::VehicleRoute,
        solve::VrpResponse,
        solve::VrpAllocationResponse,
    )),
    modifiers(&NoSecurity),
    tags(
        (name = "Routing", description = "Pass-throughs to osrm-routed, with caching and validation"),
        (name = "Optimisation", description = "Depot allocation and per-vehicle routing"),
        (name = "Infrastructure", description = "Probes and metrics; never rate limited"),
    )
)]
pub struct ApiDoc;

/// The gateway has no authentication of its own; it is expected to sit behind
/// something that does. Stated explicitly so the absence reads as a decision.
struct NoSecurity;

impl Modify for NoSecurity {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let _: Option<&SecurityScheme> = None;
        openapi.security = None;
    }
}

/// Render the document as JSON.
pub fn document() -> String {
    ApiDoc::openapi().to_pretty_json().unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn doc() -> serde_json::Value {
        serde_json::from_str(&document()).expect("the generated document is valid JSON")
    }

    /// Every route the gateway serves must appear, or clients generated from
    /// this document will be missing endpoints that exist.
    #[test]
    fn every_served_path_is_documented() {
        let doc = doc();
        let paths = doc["paths"].as_object().expect("paths object");
        for expected in ["/route", "/matrix", "/matrix-graph", "/match", "/trip", "/nearest",
                         "/vrp", "/vrp/allocate", "/health", "/ready", "/metrics"] {
            assert!(paths.contains_key(expected), "{expected} is missing from the document");
        }
        // The tile path is templated, so it is matched by prefix.
        assert!(paths.keys().any(|p| p.starts_with("/tile/")), "no tile path documented");
    }

    #[test]
    fn request_models_are_present() {
        let doc = doc();
        let schemas = doc["components"]["schemas"].as_object().expect("schemas object");
        for model in ["RouteRequest", "MatrixRequest", "MatchRequest", "TripRequest",
                      "NearestRequest", "VrpRequest", "Coordinate", "Stop"] {
            assert!(schemas.contains_key(model), "{model} is missing from components");
        }
    }

    #[test]
    fn vrp_responses_are_described_by_their_own_types() {
        let doc = doc();
        let schemas = doc["components"]["schemas"].as_object().unwrap();
        assert!(schemas.contains_key("VrpResponse"));
        assert!(schemas.contains_key("VehicleRoute"));
        assert!(schemas.contains_key("VrpAllocationResponse"));
    }

    #[test]
    fn endpoints_reference_their_request_bodies() {
        let doc = doc();
        let body = &doc["paths"]["/route"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"];
        assert_eq!(body.as_str(), Some("#/components/schemas/RouteRequest"));
    }

    #[test]
    fn the_document_declares_no_authentication() {
        assert!(doc().get("security").is_none());
    }

    // ---- equivalence with the FastAPI implementation ------------------------
    //
    // The FastAPI gateway is still in the tree as the rollback target, and its
    // schema is what clients have been generated from. These check the two
    // documents describe the same API, so a divergence introduced here shows up
    // as a test failure rather than as a client that mysteriously stops
    // matching the server. Refresh the reference with `make openapi-reference`.
    //
    // When FastAPI is removed, delete the reference file, this module and the
    // make target together -- there is nothing left to compare against, and a
    // frozen reference would start failing for the wrong reason.

    const FASTAPI_REFERENCE: &str = include_str!("../fastapi-openapi.reference.json");

    /// Fields FastAPI describes that this port deliberately does not implement,
    /// each with the reason. Anything not listed here is a real divergence.
    const ACCEPTED_EXTRA_FIELDS: &[(&str, &str, &str)] = &[
        ("VrpRequest", "vehicle_count",
         "accepted and never read by vrp_service.py; vehicles are implied by           ceil(stops / min(VRP_CHUNK_SIZE, capacity))"),
        ("ValidationError", "ctx",
         "pydantic's error taxonomy is not reproduced; see error.rs"),
        ("ValidationError", "input",
         "pydantic's error taxonomy is not reproduced; see error.rs"),
    ];

    fn reference() -> serde_json::Value {
        serde_json::from_str(FASTAPI_REFERENCE).expect("the reference is valid JSON")
    }

    /// Resolve `allOf` composition into the flat field set a client would see.
    ///
    /// utoipa encodes a `#[serde(flatten)]` field as composition while pydantic
    /// inlines it, so the documents differ in shape while describing the same
    /// request. Comparing resolved fields is the comparison that means anything.
    fn fields(schemas: &serde_json::Value, name: &str) -> std::collections::BTreeSet<String> {
        let mut found = std::collections::BTreeSet::new();
        let Some(schema) = schemas.get(name) else { return found };
        if let Some(props) = schema.get("properties").and_then(|p| p.as_object()) {
            found.extend(props.keys().cloned());
        }
        for part in schema.get("allOf").and_then(|a| a.as_array()).into_iter().flatten() {
            if let Some(reference) = part.get("$ref").and_then(|r| r.as_str()) {
                let target = reference.rsplit('/').next().unwrap_or_default();
                if target != name {
                    found.extend(fields(schemas, target));
                }
            } else if let Some(props) = part.get("properties").and_then(|p| p.as_object()) {
                found.extend(props.keys().cloned());
            }
        }
        found
    }

    /// Normalise the tile path: FastAPI carries the `.mvt` suffix in the
    /// template, axum captures it as part of the final segment.
    fn normalise(path: &str) -> String {
        path.replace("/tile/{profile}/{z}/{x}/{y}.mvt", "/tile/{profile}/{z}/{x}/{y}")
    }

    fn operations(document: &serde_json::Value) -> std::collections::BTreeSet<String> {
        let mut found = std::collections::BTreeSet::new();
        for (path, item) in document["paths"].as_object().into_iter().flatten() {
            for method in item.as_object().into_iter().flatten().map(|(m, _)| m) {
                found.insert(format!("{} {}", method.to_uppercase(), normalise(path)));
            }
        }
        found
    }

    #[test]
    fn documents_the_same_operations_as_fastapi() {
        let (generated, expected) = (operations(&doc()), operations(&reference()));
        assert_eq!(generated, expected,
                   "the two documents disagree about which endpoints exist");
    }

    #[test]
    fn documents_the_same_request_body_per_endpoint() {
        let (generated, expected) = (doc(), reference());
        for (path, item) in expected["paths"].as_object().into_iter().flatten() {
            for (method, operation) in item.as_object().into_iter().flatten() {
                let body = |op: &serde_json::Value| {
                    op["requestBody"]["content"]["application/json"]["schema"]["$ref"]
                        .as_str().map(|r| r.rsplit('/').next().unwrap_or_default().to_string())
                };
                let Some(want) = body(operation) else { continue };
                let got = generated["paths"][&normalise(path)][method].clone();
                assert_eq!(body(&got).as_deref(), Some(want.as_str()),
                           "{method} {path} takes a different request body");
            }
        }
    }

    /// The check that matters most: every field FastAPI documents is documented
    /// here too, unless it is a named, reasoned omission.
    #[test]
    fn documents_the_same_model_fields_as_fastapi() {
        let (generated, expected) = (doc(), reference());
        let (gs, es) = (&generated["components"]["schemas"], &expected["components"]["schemas"]);

        let mut unexplained = Vec::new();
        for name in es.as_object().into_iter().flatten().map(|(n, _)| n) {
            if gs.get(name).is_none() {
                continue; // FastAPI-only wrappers such as HTTPValidationError.
            }
            for missing in fields(es, name).difference(&fields(gs, name)) {
                let accepted = ACCEPTED_EXTRA_FIELDS.iter()
                    .any(|(model, field, _)| model == name && field == missing);
                if !accepted {
                    unexplained.push(format!("{name}.{missing}"));
                }
            }
        }
        assert!(unexplained.is_empty(),
                "fields FastAPI documents and this port does not, with no recorded reason: {unexplained:?}");
    }
}
